# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'ZZBeautyCamra' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZZBeautyCamra
  pod 'GPUImage', '~> 0.1.7'
  pod 'CycleScrollView', '~> 1.0.0'
  pod 'Toast', '~> 4.0.0'
  target 'ZZBeautyCamraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZZBeautyCamraUITests' do
    # Pods for testing
  end

end
