# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ZZBeautyCamra' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ZZBeautyCamra
  pod 'GPUImage', '~> 0.1.7'
  target 'ZZBeautyCamraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZZBeautyCamraUITests' do
    # Pods for testing
  end

end
